# codecov configuration see https://docs.codecov.io/docs/coverage-configuration
ignore:
  - "fuse/**"  # fuse can not be tested with coverage
coverage:
  range: 50..75
  round: down
  precision: 2
  status:
    project:
      default:
        target: 75
