dist: trusty
sudo: required
language: cpp

cache:
  apt: true
  directories:
    - grpc
    - boost_1_65_1

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - build-essential
      - autoconf
      - libtool
      - git
      - curl
      - protobuf-compiler

env:
  - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
  - pwd
  - eval "${MATRIX_EVAL}"
  - git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
  - cd grpc
  - git submodule update --init
  - make CFLAGS='-Wno-implicit-fallthrough -w' CXXFLAGS='-Wno-implicit-fallthrough -w'
  - sudo make install
  - cd third_party/protobuf
  - ./autogen.sh
  - ./configure && make
  - sudo make install
  - cd
  - curl -O -L https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.tar.bz2
  - tar xvjf boost_1_65_1.tar.bz2 && cd boost_1_65_1
  - ./bootstrap.sh
  - ./b2
  - cd ../../..

script:
  - protoc --version
  - cmake .
  - cmake --build . -- -j2
  - ctest -j2
