FROM ubuntu:24.04 AS build

#
# install dependencies
#
ENV DEBIAN_FRONTEND=noninteractive 
RUN apt update \
    && apt -y install build-essential \
            git \
            cmake \
            ninja-build \
            autoconf \
            pkg-config \
            pipx \
    && pipx ensurepath \
    && . ~/.profile \
    && pipx install conan \

#
# build project
#
COPY . /opt/chord
WORKDIR /opt/chord

RUN rm -rf build \
    && conan profile detect -f \
    && conan install . --build=missing --output-folder=build \
    && cd build \
    && cmake .. \
        -G Ninja \
        -DBUILD_GMOCK=OFF \
        -DBUILD_TESTING=OFF \
        -DINSTALL_GTEST=OFF \
        -Dchord_BUILD_TESTS=OFF \
        -DCMAKE_BUILD_TYPE=Release \
    && cmake --build . -- -j$(nproc)

#
# create chroot env
#
WORKDIR /opt/chord/build/bin
RUN mkdir -p /chroot/bin \
    && cp ./chord /chroot/bin \
    && ldd ./chord | grep -oP '/[^ ]*' | xargs -I '{}' cp --parents -v '{}' /chroot/

#
# node image
#
FROM scratch

COPY --from=build /chroot /

EXPOSE 50050

ENTRYPOINT ["/bin/chord"]
CMD ["-b"]
