version: 1

register_shutdown_handler: Yes

##data
monitor: Yes
data-directory: "./data2"
meta-directory: "./meta2"

##networking
bind-addr: "0.0.0.0:50052"
join-addr: "0.0.0.0:50050"
bootstrap: No
no-controller: Yes

## details
stabilize_ms: 10000
check_ms: 10000

#uuid: "20"
uuid: "57896044620000006678280936031721331295010511669633703118152976382517355479040"
#2^256/4*3
#uuid: "86844066927987146567678238756515930889952488499230423029593188005934847229952"

logging:
  level: trace
  sinks:
    CONSOLE_SINK:
      type: "console"
    FILE_SINK:
      type: "file-rotating"
      path: "logs/chord2.log"
  loggers:
    CHORD_LOG:
      sinks: [FILE_SINK]
      filter: "^chord[.](?!fs)"
    CHORD_FS_LOG:
      sinks: [CONSOLE_SINK]
      filter: "^chord[.]fs"
      level: trace
