version: 1

##data
data-directory: "./data1"
meta-directory: "./meta1"

##networking
bind-addr: "0.0.0.0:50051"
join-addr: "0.0.0.0:50050"
bootstrap: No
no-controller: Yes

## details
stabilize_ms: 10000
check_ms: 10000

#uuid: "4444444444"
#uuid: "5"
