version: 1

##data
data-directory: "./data1"
meta-directory: "./meta1"

##networking
bind-addr: "0.0.0.0:50051"
join-addr: "0.0.0.0:50050"
bootstrap: No
no-controller: Yes

## details
stabilize_ms: 10000
check_ms: 10000

## replication / striping
#replication-count: 3

#uuid: "10"
#2^256 / 2
uuid: "57896044620000006678280936031721331295010511669633703118152976382517355479040"

logging:
  level: trace
  sinks:
    CONSOLE_SINK:
      type: "console"
    FILE_SINK:
      type: "file-rotating"
      path: "logs/chord1.log"
  loggers:
    CHORD_LOG:
      sinks: [FILE_SINK]
      filter: "^chord[.](?!fs)"
    CHORD_FS_LOG:
      sinks: [CONSOLE_SINK]
      filter: "^chord[.]fs"
      level: trace
