version: 1

##data
data-directory: "./data3"
meta-directory: "./meta3"

##networking
bind-addr: "0.0.0.0:50053"
join-addr: "0.0.0.0:50051"
bootstrap: No
no-controller: Yes

## details
stabilize_ms: 10000
check_ms: 10000

#uuid: "999999999999999999995555555555555555"
uuid: "20"
