version: 1

##data
data-directory: "./data3"
meta-directory: "./meta3"

##networking
bind-addr: "0.0.0.0:50053"
join-addr: "0.0.0.0:50051"
bootstrap: No
no-controller: Yes

## details
stabilize_ms: 1000
check_ms: 1000

#uuid: "999999999999999999995555555555555555"
#uuid: "20"
uuid: "86844066927987146567678238756515930889952488499230423029593188005934847229952"

logging:
  level: trace
  sinks:
    CONSOLE_SINK:
      type: "console"
    FILE_SINK:
      type: "file-rotating"
      path: "logs/chord3.log"
  loggers:
    CHORD_LOG:
      sinks: [FILE_SINK]
      filter: "^chord[.](?!fs)"
    CHORD_FS_LOG:
      sinks: [CONSOLE_SINK]
      filter: "^chord[.]fs"
      level: trace
